export const link: string;
export const link_container: string;
export const linkContainer: string;
export const category_content: string;
export const categoryContent: string;
export const category_list: string;
export const categoryList: string;
export const category_title: string;
export const categoryTitle: string;
